development:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: fswd_chatroom_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: fswd_chat_room_production
  ssl_params:
    verify_mode: 0    